# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_typee',
            new_name='file_type',
        ),
    ]
